# -*- coding: utf-8 -*-
"""social-media-and-mental-health-balance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-8Q7sGa0KHlLlJrXBC4nsYm2S9O9cmL

This dataset has been got from [Kaggle](https://www.kaggle.com/).  
[Social Media and Mental Health Balance](https://www.kaggle.com/datasets/ayeshaimran123/social-media-and-mental-health-balance)
"""

import pandas as pd
df = pd.read_csv('Mental_Health_and_Social_Media_Balance_Dataset.csv')
df.columns

"""All the column headers."""

df.head()

"""The first five rows of data."""

df.info()

"""- There are 500 entries 0-499.
- There are no null values (good thing)
- Gender and Social_Media_Platform are categorical variables, rest are numeric
"""

df.describe()

"""A brief statistical metadata about the dataset."""

import matplotlib.pyplot as plt

df.hist(figsize=(10,8))
plt.tight_layout()
plt.show()

"""Histogram for all numeric columns."""

df.select_dtypes(include=['number']).skew()

"""Happiness_Index is moderately left skewed.  
There are more happy people in this dataset.
"""

import seaborn as sns
sns.heatmap(df.select_dtypes(include=['number']).corr(), annot=True, cmap='coolwarm')
plt.show()

"""Happiness_Index(1-10) is  
- Highly inversely correlated to Daily_Screen_Time(hrs)
- Highly correlated to Sleep_Quality(1-10)
- Highly inversely correlated to Stress_Level(1-10)

Regression will be used to predict the Happiness_Index(1-10) based on variables.

Preprocessing

Drop the User_ID column
"""

df.drop(columns=['User_ID'], inplace=True)

df.head()

"""Encoding categorical variable Gender"""

df['Gender'].unique()

df = pd.get_dummies(df, columns=['Gender'], drop_first=True)

"""Encoding categorical variable Social_Media_Platform"""

df['Social_Media_Platform'].unique()

df = pd.get_dummies(df, columns=['Social_Media_Platform'], drop_first=True)

df.head()

"""No Normalization because we are going to use a tree-based regressor"""